### ISSUE TITLE
Предложение: сделать документацию по всем методам объекта Client

### ISSUE THREAD

**Issue by atnartur** [zxqfox/megaplanjs#3]
Как насчет создания документации по всем методам объекта Client? Если я сделаю такую документацию в виде md-файла или JSDoc-комментариев, Вы примите pull request?

**Comment by qfox** [comment]
Конечно, спасибо!

**Comment by qfox** [comment]
@atnartur Добавь, плз, в настройки гита имя и почту ;-) `git config --global user.email ...` [Конфигурирование Git](http://git-scm.com/book/ru/v1/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-Git-%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-Git)

От тебя не убудет, а гиту (и гитхабу) проще.

**Comment by atnartur** [comment]
Дошли руки до документации. Начал делать ее на [ветке feat_docs](https://github.com/atnartur/megaplanjs/tree/feat_docs). Документацию можно сгенерировать с помощью `npm run docs`. 

Делаю к каждому методу подсказку со ссылкой на [официальную документацию](https://help.megaplan.ru/API).
Вопрос: что за react() находится вот [здесь](https://github.com/atnartur/megaplanjs/blob/feat_docs/lib/megaplan/client.js#L411)? Никак не могу найти упоминание о нем. Про uri shortcuts знаю. Содержимое переменной не помогло найти метод в официальной документации.

**Comment by qfox** [comment]
Приехало вот отсуда:
https://github.com/IShumihin/megaplan/blob/master/megaplan/megaplan.py#L127-L129

Возможно, это что-то нелегальное и никому не нужное.

**Comment by atnartur** [comment]
Видимо, устарело. SdfNotify вообще нет нигде. Убирать?

**Comment by qfox** [comment]
Кажется, что да. У нас же 1.0 еще не выпущено?

**Comment by atnartur** [comment]
0.2 было только. Подождите, я для событий методы сделаю завтра)

**Comment by qfox** [comment]
Мы никуда не торопимся, все от тебя зависит ;-) Как скажешь — так и сделаем

**Comment by atnartur** [comment]
По документации еще есть какие-нибудь замечания?

**Comment by qfox** [comment]
Замечаний нет. Выглядит хорошо.
